### ISSUE TITLE
New ndk r19 and above compiling ffmpeg

### ISSUE THREAD

**Issue by raghunandankavi2010** [ejoker88/FFmpeg-3.4-Android#3]
I followed one of your videos on youtube and the link to your blog. https://developer.android.com/ndk/guides/standalone_toolchain says you need to use the make_standalone_toolchain.py is not necessary. So in that case. what should be done. Just go ahead with the rest of the tutorial?.

**Comment by ejoker88** [comment]
Hello, Sorry for late reply, as I was not on Github long time due to personal reasons. You can still go ahead with rest of the tutorial. Earlier NDK was not well organized and it was good idea to export Toolchains in seperate folder. But with new NDK you can compile without creating or exporting Toolchains in seperate folder. Therefore, Google has mentioned that it is not necessary. Anyway you can still follow my video and you should be able to compile the library as I just did few days back with 4.0 version and latest NDK. Or you need to update toolchain paths in all Shell or build files from this repo yourself, if you can follow instructions from page https://developer.android.com/ndk/guides/standalone_toolchain. If you still need help, then please let me know.

**Comment by raghunandankavi2010** [comment]
Thank you.
